// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
    entity_type, entity_id, action_type,
    field_name, old_value, new_value,
    performed_by_id, performed_by_name, created_on
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertAuditLogParams struct {
	EntityType      string
	EntityID        uuid.UUID
	ActionType      string
	FieldName       *string
	OldValue        *string
	NewValue        *string
	PerformedByID   uuid.UUID
	PerformedByName string
	CreatedOn       time.Time
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.ActionType,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
		arg.PerformedByID,
		arg.PerformedByName,
		arg.CreatedOn,
	)
	return err
}
