// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_controls.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const listActiveCCIDsForUser = `-- name: ListActiveCCIDsForUser :many
SELECT cc_id FROM change_controls
WHERE (change_owner_id = $1 OR assigned_approver_id = $1)
    AND current_state NOT IN ('Closed', 'Cancelled')
ORDER BY cc_id
`

func (q *Queries) ListActiveCCIDsForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCCIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var cc_id string
		if err := rows.Scan(&cc_id); err != nil {
			return nil, err
		}
		items = append(items, cc_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
