// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_controls.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countChangeControls = `-- name: CountChangeControls :one
SELECT COUNT(*) 
FROM change_controls cc
    JOIN        users owner     ON owner.id = cc.change_owner_id
    LEFT JOIN   users approver  ON approver.id  = cc.assigned_approver_id
WHERE 1=1
  -- 1. Owner filter (UUID)
  AND ($1::uuid IS NULL 
       OR cc.change_owner_id = $1)

  -- 2. Assigned Approver filter (UUID)
  AND ($2::uuid IS NULL 
       OR cc.assigned_approver_id = $2)

  -- 3. State filter (text)
  AND ($3::text IS NULL 
       OR cc.current_state = $3)

  -- 4. Created after filter (date, inclusive >=)
  AND ($4::date IS NULL 
       OR cc.created_on >= $4)

  -- 5. Created before filter (date, exclusive < with +1 day buffer)
  AND ($5::date IS NULL 
       OR cc.created_on < $5 + INTERVAL '1 day')

  -- 6. Search filter (text across multiple columns)
  AND ($6::text IS NULL 
       OR cc.cc_id          ILIKE '%' || $6 || '%'
       OR cc.change_title   ILIKE '%' || $6 || '%'
       OR owner.full_name   ILIKE '%' || $6 || '%')
`

type CountChangeControlsParams struct {
	OwnerID            *uuid.UUID
	AssignedApproverID *uuid.UUID
	State              *string
	CreatedAfter       *time.Time
	CreatedBefore      *time.Time
	Search             *string
}

func (q *Queries) CountChangeControls(ctx context.Context, arg CountChangeControlsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChangeControls,
		arg.OwnerID,
		arg.AssignedApproverID,
		arg.State,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChangeControl = `-- name: CreateChangeControl :one
INSERT INTO change_controls (change_owner_id, last_updated_by_id)
VALUES ($1, $2)
RETURNING id, cc_number, cc_id, current_state, change_owner_id, last_updated_by_id, created_on, last_updated_on, change_title, change_description, change_type, change_category, department_function, affected_systems_modules, proposed_implementation_date, target_closure_date, implementation_window_start, implementation_window_end, reason_for_change, business_impact, expected_downtime, requires_testing, requires_training, risk_rationale, key_risks_mitigations, high_level_implementation_plan, validation_approach, success_criteria, rollback_backout_plan, actual_implementation_date, post_implementation_issues, implementation_summary, deviations_from_plan, validation_performed, assigned_approver_id, comments_for_approver, decision, risk_level, decision_comments, implementation_approval_by_id, implementation_approval_on, final_decision, final_comments, final_approval_by_id, final_approval_on, implementation_approval_status, final_approval_status, actual_closure_date, comments, cancellation_reason
`

type CreateChangeControlParams struct {
	ChangeOwnerID   uuid.UUID
	LastUpdatedByID uuid.UUID
}

func (q *Queries) CreateChangeControl(ctx context.Context, arg CreateChangeControlParams) (ChangeControl, error) {
	row := q.db.QueryRowContext(ctx, createChangeControl, arg.ChangeOwnerID, arg.LastUpdatedByID)
	var i ChangeControl
	err := row.Scan(
		&i.ID,
		&i.CcNumber,
		&i.CcID,
		&i.CurrentState,
		&i.ChangeOwnerID,
		&i.LastUpdatedByID,
		&i.CreatedOn,
		&i.LastUpdatedOn,
		&i.ChangeTitle,
		&i.ChangeDescription,
		&i.ChangeType,
		&i.ChangeCategory,
		&i.DepartmentFunction,
		&i.AffectedSystemsModules,
		&i.ProposedImplementationDate,
		&i.TargetClosureDate,
		&i.ImplementationWindowStart,
		&i.ImplementationWindowEnd,
		&i.ReasonForChange,
		&i.BusinessImpact,
		&i.ExpectedDowntime,
		&i.RequiresTesting,
		&i.RequiresTraining,
		&i.RiskRationale,
		&i.KeyRisksMitigations,
		&i.HighLevelImplementationPlan,
		&i.ValidationApproach,
		&i.SuccessCriteria,
		&i.RollbackBackoutPlan,
		&i.ActualImplementationDate,
		&i.PostImplementationIssues,
		&i.ImplementationSummary,
		&i.DeviationsFromPlan,
		&i.ValidationPerformed,
		&i.AssignedApproverID,
		&i.CommentsForApprover,
		&i.Decision,
		&i.RiskLevel,
		&i.DecisionComments,
		&i.ImplementationApprovalByID,
		&i.ImplementationApprovalOn,
		&i.FinalDecision,
		&i.FinalComments,
		&i.FinalApprovalByID,
		&i.FinalApprovalOn,
		&i.ImplementationApprovalStatus,
		&i.FinalApprovalStatus,
		&i.ActualClosureDate,
		&i.Comments,
		&i.CancellationReason,
	)
	return i, err
}

const getChangeControlByCcID = `-- name: GetChangeControlByCcID :one
SELECT
    cc.id, cc.cc_number, cc.cc_id, cc.current_state, cc.change_owner_id, cc.last_updated_by_id, cc.created_on, cc.last_updated_on, cc.change_title, cc.change_description, cc.change_type, cc.change_category, cc.department_function, cc.affected_systems_modules, cc.proposed_implementation_date, cc.target_closure_date, cc.implementation_window_start, cc.implementation_window_end, cc.reason_for_change, cc.business_impact, cc.expected_downtime, cc.requires_testing, cc.requires_training, cc.risk_rationale, cc.key_risks_mitigations, cc.high_level_implementation_plan, cc.validation_approach, cc.success_criteria, cc.rollback_backout_plan, cc.actual_implementation_date, cc.post_implementation_issues, cc.implementation_summary, cc.deviations_from_plan, cc.validation_performed, cc.assigned_approver_id, cc.comments_for_approver, cc.decision, cc.risk_level, cc.decision_comments, cc.implementation_approval_by_id, cc.implementation_approval_on, cc.final_decision, cc.final_comments, cc.final_approval_by_id, cc.final_approval_on, cc.implementation_approval_status, cc.final_approval_status, cc.actual_closure_date, cc.comments, cc.cancellation_reason,
    owner.full_name        AS owner_name,
    updater.full_name      AS updater_name,
    approver.full_name     AS approver_name,
    impl_by.full_name      AS impl_approval_by_name,
    final_by.full_name     AS final_approval_by_name
FROM change_controls cc
    JOIN      users owner     ON owner.id     = cc.change_owner_id
    JOIN      users updater   ON updater.id   = cc.last_updated_by_id
    LEFT JOIN users approver  ON approver.id  = cc.assigned_approver_id
    LEFT JOIN users impl_by   ON impl_by.id   = cc.implementation_approval_by_id
    LEFT JOIN users final_by  ON final_by.id  = cc.final_approval_by_id
WHERE cc.cc_id = $1
`

type GetChangeControlByCcIDRow struct {
	ChangeControl       ChangeControl
	OwnerName           string
	UpdaterName         string
	ApproverName        *string
	ImplApprovalByName  *string
	FinalApprovalByName *string
}

func (q *Queries) GetChangeControlByCcID(ctx context.Context, ccID string) (GetChangeControlByCcIDRow, error) {
	row := q.db.QueryRowContext(ctx, getChangeControlByCcID, ccID)
	var i GetChangeControlByCcIDRow
	err := row.Scan(
		&i.ChangeControl.ID,
		&i.ChangeControl.CcNumber,
		&i.ChangeControl.CcID,
		&i.ChangeControl.CurrentState,
		&i.ChangeControl.ChangeOwnerID,
		&i.ChangeControl.LastUpdatedByID,
		&i.ChangeControl.CreatedOn,
		&i.ChangeControl.LastUpdatedOn,
		&i.ChangeControl.ChangeTitle,
		&i.ChangeControl.ChangeDescription,
		&i.ChangeControl.ChangeType,
		&i.ChangeControl.ChangeCategory,
		&i.ChangeControl.DepartmentFunction,
		&i.ChangeControl.AffectedSystemsModules,
		&i.ChangeControl.ProposedImplementationDate,
		&i.ChangeControl.TargetClosureDate,
		&i.ChangeControl.ImplementationWindowStart,
		&i.ChangeControl.ImplementationWindowEnd,
		&i.ChangeControl.ReasonForChange,
		&i.ChangeControl.BusinessImpact,
		&i.ChangeControl.ExpectedDowntime,
		&i.ChangeControl.RequiresTesting,
		&i.ChangeControl.RequiresTraining,
		&i.ChangeControl.RiskRationale,
		&i.ChangeControl.KeyRisksMitigations,
		&i.ChangeControl.HighLevelImplementationPlan,
		&i.ChangeControl.ValidationApproach,
		&i.ChangeControl.SuccessCriteria,
		&i.ChangeControl.RollbackBackoutPlan,
		&i.ChangeControl.ActualImplementationDate,
		&i.ChangeControl.PostImplementationIssues,
		&i.ChangeControl.ImplementationSummary,
		&i.ChangeControl.DeviationsFromPlan,
		&i.ChangeControl.ValidationPerformed,
		&i.ChangeControl.AssignedApproverID,
		&i.ChangeControl.CommentsForApprover,
		&i.ChangeControl.Decision,
		&i.ChangeControl.RiskLevel,
		&i.ChangeControl.DecisionComments,
		&i.ChangeControl.ImplementationApprovalByID,
		&i.ChangeControl.ImplementationApprovalOn,
		&i.ChangeControl.FinalDecision,
		&i.ChangeControl.FinalComments,
		&i.ChangeControl.FinalApprovalByID,
		&i.ChangeControl.FinalApprovalOn,
		&i.ChangeControl.ImplementationApprovalStatus,
		&i.ChangeControl.FinalApprovalStatus,
		&i.ChangeControl.ActualClosureDate,
		&i.ChangeControl.Comments,
		&i.ChangeControl.CancellationReason,
		&i.OwnerName,
		&i.UpdaterName,
		&i.ApproverName,
		&i.ImplApprovalByName,
		&i.FinalApprovalByName,
	)
	return i, err
}

const listActiveCCIDsForUser = `-- name: ListActiveCCIDsForUser :many
SELECT cc_id FROM change_controls
WHERE (change_owner_id = $1 OR assigned_approver_id = $1)
    AND current_state NOT IN ('Closed', 'Cancelled')
ORDER BY cc_id
`

func (q *Queries) ListActiveCCIDsForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCCIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var cc_id string
		if err := rows.Scan(&cc_id); err != nil {
			return nil, err
		}
		items = append(items, cc_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeControls = `-- name: ListChangeControls :many
SELECT
    cc.id,
    cc.cc_id,
    cc.change_title,
    cc.current_state, 
    cc.change_owner_id, 
    owner.full_name                                 AS owner_name, 
    cc.assigned_approver_id, approver.full_name     AS approver_name, 
    cc.created_on, 
    cc.last_updated_on
FROM change_controls cc
    JOIN        users owner     ON owner.id = cc.change_owner_id
    LEFT JOIN   users approver  ON approver.id  = cc.assigned_approver_id
WHERE 1=1
  -- 1. Owner filter (UUID)
  AND ($1::uuid IS NULL 
       OR cc.change_owner_id = $1)

  -- 2. Assigned Approver filter (UUID)
  AND ($2::uuid IS NULL 
       OR cc.assigned_approver_id = $2)

  -- 3. State filter (text)
  AND ($3::text IS NULL 
       OR cc.current_state = $3)

  -- 4. Created after filter (date, inclusive >=)
  AND ($4::date IS NULL 
       OR cc.created_on >= $4)

  -- 5. Created before filter (date, exclusive < with +1 day buffer)
  AND ($5::date IS NULL 
       OR cc.created_on < $5 + INTERVAL '1 day')

  -- 6. Search filter (text across multiple columns)
  AND ($6::text IS NULL 
       OR cc.cc_id          ILIKE '%' || $6 || '%'
       OR cc.change_title   ILIKE '%' || $6 || '%'
       OR owner.full_name   ILIKE '%' || $6 || '%')
ORDER BY cc.last_updated_on DESC
LIMIT $8 OFFSET $7
`

type ListChangeControlsParams struct {
	OwnerID            *uuid.UUID
	AssignedApproverID *uuid.UUID
	State              *string
	CreatedAfter       *time.Time
	CreatedBefore      *time.Time
	Search             *string
	Offset             int32
	Limit              int32
}

type ListChangeControlsRow struct {
	ID                 uuid.UUID
	CcID               string
	ChangeTitle        *string
	CurrentState       string
	ChangeOwnerID      uuid.UUID
	OwnerName          string
	AssignedApproverID *uuid.UUID
	ApproverName       *string
	CreatedOn          time.Time
	LastUpdatedOn      time.Time
}

func (q *Queries) ListChangeControls(ctx context.Context, arg ListChangeControlsParams) ([]ListChangeControlsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChangeControls,
		arg.OwnerID,
		arg.AssignedApproverID,
		arg.State,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangeControlsRow
	for rows.Next() {
		var i ListChangeControlsRow
		if err := rows.Scan(
			&i.ID,
			&i.CcID,
			&i.ChangeTitle,
			&i.CurrentState,
			&i.ChangeOwnerID,
			&i.OwnerName,
			&i.AssignedApproverID,
			&i.ApproverName,
			&i.CreatedOn,
			&i.LastUpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
