// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_controls.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChangeControl = `-- name: CreateChangeControl :one
INSERT INTO change_controls (change_owner_id, last_updated_by_id)
VALUES ($1, $2)
RETURNING id, cc_number, cc_id, current_state, change_owner_id, last_updated_by_id, created_on, last_updated_on, change_title, change_description, change_type, change_category, department_function, affected_systems_modules, proposed_implementation_date, target_closure_date, implementation_window_start, implementation_window_end, reason_for_change, business_impact, expected_downtime, requires_testing, requires_training, risk_rationale, key_risks_mitigations, high_level_implementation_plan, validation_approach, success_criteria, rollback_backout_plan, actual_implementation_date, post_implementation_issues, implementation_summary, deviations_from_plan, validation_performed, assigned_approver_id, comments_for_approver, decision, risk_level, decision_comments, implementation_approval_by_id, implementation_approval_on, final_decision, final_comments, final_approval_by_id, final_approval_on, implementation_approval_status, final_approval_status, actual_closure_date, comments, cancellation_reason
`

type CreateChangeControlParams struct {
	ChangeOwnerID   uuid.UUID
	LastUpdatedByID uuid.UUID
}

func (q *Queries) CreateChangeControl(ctx context.Context, arg CreateChangeControlParams) (ChangeControl, error) {
	row := q.db.QueryRowContext(ctx, createChangeControl, arg.ChangeOwnerID, arg.LastUpdatedByID)
	var i ChangeControl
	err := row.Scan(
		&i.ID,
		&i.CcNumber,
		&i.CcID,
		&i.CurrentState,
		&i.ChangeOwnerID,
		&i.LastUpdatedByID,
		&i.CreatedOn,
		&i.LastUpdatedOn,
		&i.ChangeTitle,
		&i.ChangeDescription,
		&i.ChangeType,
		&i.ChangeCategory,
		&i.DepartmentFunction,
		&i.AffectedSystemsModules,
		&i.ProposedImplementationDate,
		&i.TargetClosureDate,
		&i.ImplementationWindowStart,
		&i.ImplementationWindowEnd,
		&i.ReasonForChange,
		&i.BusinessImpact,
		&i.ExpectedDowntime,
		&i.RequiresTesting,
		&i.RequiresTraining,
		&i.RiskRationale,
		&i.KeyRisksMitigations,
		&i.HighLevelImplementationPlan,
		&i.ValidationApproach,
		&i.SuccessCriteria,
		&i.RollbackBackoutPlan,
		&i.ActualImplementationDate,
		&i.PostImplementationIssues,
		&i.ImplementationSummary,
		&i.DeviationsFromPlan,
		&i.ValidationPerformed,
		&i.AssignedApproverID,
		&i.CommentsForApprover,
		&i.Decision,
		&i.RiskLevel,
		&i.DecisionComments,
		&i.ImplementationApprovalByID,
		&i.ImplementationApprovalOn,
		&i.FinalDecision,
		&i.FinalComments,
		&i.FinalApprovalByID,
		&i.FinalApprovalOn,
		&i.ImplementationApprovalStatus,
		&i.FinalApprovalStatus,
		&i.ActualClosureDate,
		&i.Comments,
		&i.CancellationReason,
	)
	return i, err
}

const listActiveCCIDsForUser = `-- name: ListActiveCCIDsForUser :many
SELECT cc_id FROM change_controls
WHERE (change_owner_id = $1 OR assigned_approver_id = $1)
    AND current_state NOT IN ('Closed', 'Cancelled')
ORDER BY cc_id
`

func (q *Queries) ListActiveCCIDsForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCCIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var cc_id string
		if err := rows.Scan(&cc_id); err != nil {
			return nil, err
		}
		items = append(items, cc_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
