// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countChangeControlsByState = `-- name: CountChangeControlsByState :many
SELECT current_state, COUNT(*) AS count
FROM change_controls
WHERE current_state <> 'Cancelled'
GROUP BY current_state
`

type CountChangeControlsByStateRow struct {
	CurrentState string
	Count        int64
}

// Cancelled is deliberately excluded: §9.5.2 lists five "active" states for the
// Overview cards. A cancelled record can still appear in recent activity.
func (q *Queries) CountChangeControlsByState(ctx context.Context) ([]CountChangeControlsByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, countChangeControlsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountChangeControlsByStateRow
	for rows.Next() {
		var i CountChangeControlsByStateRow
		if err := rows.Scan(&i.CurrentState, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDraftsForUser = `-- name: CountDraftsForUser :one
SELECT COUNT(*) FROM change_controls
WHERE change_owner_id = $1 AND current_state = 'Initiated'
`

func (q *Queries) CountDraftsForUser(ctx context.Context, changeOwnerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDraftsForUser, changeOwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingApprovalsForUser = `-- name: CountPendingApprovalsForUser :one
SELECT COUNT(*) FROM change_controls
WHERE assigned_approver_id = $1
  AND current_state IN ('Pending Implementation Approval', 'Pending Final Approval')
`

func (q *Queries) CountPendingApprovalsForUser(ctx context.Context, assignedApproverID *uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingApprovalsForUser, assignedApproverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDraftsForUser = `-- name: ListDraftsForUser :many
SELECT cc_id, change_title, current_state
FROM change_controls
WHERE change_owner_id = $1 AND current_state = 'Initiated'
ORDER BY last_updated_on DESC
LIMIT $2
`

type ListDraftsForUserParams struct {
	ChangeOwnerID uuid.UUID
	Limit         int32
}

type ListDraftsForUserRow struct {
	CcID         string
	ChangeTitle  *string
	CurrentState string
}

func (q *Queries) ListDraftsForUser(ctx context.Context, arg ListDraftsForUserParams) ([]ListDraftsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDraftsForUser, arg.ChangeOwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftsForUserRow
	for rows.Next() {
		var i ListDraftsForUserRow
		if err := rows.Scan(&i.CcID, &i.ChangeTitle, &i.CurrentState); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingApprovalsForUser = `-- name: ListPendingApprovalsForUser :many
SELECT cc_id, change_title, current_state
FROM change_controls
WHERE assigned_approver_id = $1
  AND current_state IN ('Pending Implementation Approval', 'Pending Final Approval')
ORDER BY last_updated_on DESC
LIMIT $2
`

type ListPendingApprovalsForUserParams struct {
	AssignedApproverID *uuid.UUID
	Limit              int32
}

type ListPendingApprovalsForUserRow struct {
	CcID         string
	ChangeTitle  *string
	CurrentState string
}

func (q *Queries) ListPendingApprovalsForUser(ctx context.Context, arg ListPendingApprovalsForUserParams) ([]ListPendingApprovalsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingApprovalsForUser, arg.AssignedApproverID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingApprovalsForUserRow
	for rows.Next() {
		var i ListPendingApprovalsForUserRow
		if err := rows.Scan(&i.CcID, &i.ChangeTitle, &i.CurrentState); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivity = `-- name: ListRecentActivity :many
SELECT cc.cc_id,
       cc.change_title,
       cc.current_state,
       cc.last_updated_on,
       updater.full_name AS last_updated_by_name
FROM change_controls cc
    JOIN users updater ON updater.id = cc.last_updated_by_id
ORDER BY cc.last_updated_on DESC
LIMIT $1
`

type ListRecentActivityRow struct {
	CcID              string
	ChangeTitle       *string
	CurrentState      string
	LastUpdatedOn     time.Time
	LastUpdatedByName string
}

func (q *Queries) ListRecentActivity(ctx context.Context, limit int32) ([]ListRecentActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentActivityRow
	for rows.Next() {
		var i ListRecentActivityRow
		if err := rows.Scan(
			&i.CcID,
			&i.ChangeTitle,
			&i.CurrentState,
			&i.LastUpdatedOn,
			&i.LastUpdatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
