// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: esignatures.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertESignature = `-- name: InsertESignature :exec
INSERT INTO esignatures
  (change_control_id, signer_id, signer_name, transition, meaning, signed_on)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertESignatureParams struct {
	ChangeControlID uuid.UUID
	SignerID        uuid.UUID
	SignerName      string
	Transition      string
	Meaning         string
	SignedOn        time.Time
}

func (q *Queries) InsertESignature(ctx context.Context, arg InsertESignatureParams) error {
	_, err := q.db.ExecContext(ctx, insertESignature,
		arg.ChangeControlID,
		arg.SignerID,
		arg.SignerName,
		arg.Transition,
		arg.Meaning,
		arg.SignedOn,
	)
	return err
}
