// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_attachments.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getFileAttachment = `-- name: GetFileAttachment :one
SELECT file_name, file_data, content_type, file_size
FROM file_attachments
WHERE change_control_id = $1 AND field_name = $2
`

type GetFileAttachmentParams struct {
	ChangeControlID uuid.UUID
	FieldName       string
}

type GetFileAttachmentRow struct {
	FileName    string
	FileData    []byte
	ContentType string
	FileSize    int64
}

func (q *Queries) GetFileAttachment(ctx context.Context, arg GetFileAttachmentParams) (GetFileAttachmentRow, error) {
	row := q.db.QueryRowContext(ctx, getFileAttachment, arg.ChangeControlID, arg.FieldName)
	var i GetFileAttachmentRow
	err := row.Scan(
		&i.FileName,
		&i.FileData,
		&i.ContentType,
		&i.FileSize,
	)
	return i, err
}

const upsertFileAttachment = `-- name: UpsertFileAttachment :one
INSERT INTO file_attachments (
    change_control_id,
    field_name,
    file_name,
    file_size,
    content_type,
    file_data,
    uploaded_by_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (change_control_id, field_name) DO UPDATE
SET file_name      = EXCLUDED.file_name,
    file_size      = EXCLUDED.file_size,
    content_type   = EXCLUDED.content_type,
    file_data      = EXCLUDED.file_data,
    uploaded_by_id = EXCLUDED.uploaded_by_id,
    uploaded_on    = NOW()
RETURNING id, change_control_id, field_name, file_name, file_size,
          content_type, uploaded_by_id, uploaded_on
`

type UpsertFileAttachmentParams struct {
	ChangeControlID uuid.UUID
	FieldName       string
	FileName        string
	FileSize        int64
	ContentType     string
	FileData        []byte
	UploadedByID    uuid.UUID
}

type UpsertFileAttachmentRow struct {
	ID              uuid.UUID
	ChangeControlID uuid.UUID
	FieldName       string
	FileName        string
	FileSize        int64
	ContentType     string
	UploadedByID    uuid.UUID
	UploadedOn      time.Time
}

func (q *Queries) UpsertFileAttachment(ctx context.Context, arg UpsertFileAttachmentParams) (UpsertFileAttachmentRow, error) {
	row := q.db.QueryRowContext(ctx, upsertFileAttachment,
		arg.ChangeControlID,
		arg.FieldName,
		arg.FileName,
		arg.FileSize,
		arg.ContentType,
		arg.FileData,
		arg.UploadedByID,
	)
	var i UpsertFileAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.ChangeControlID,
		&i.FieldName,
		&i.FileName,
		&i.FileSize,
		&i.ContentType,
		&i.UploadedByID,
		&i.UploadedOn,
	)
	return i, err
}
