// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE ($1::boolean IS NULL OR is_active = $1)
`

func (q *Queries) CountUsers(ctx context.Context, isActive *bool) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, isActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, email, hashed_password, role)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, full_name, email, hashed_password, role, is_active, created_on, updated_on
`

type CreateUserParams struct {
	FullName       string
	Email          string
	HashedPassword string
	Role           string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.HashedPassword,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.IsActive,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, hashed_password, role, is_active, created_on, updated_on FROM users
WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.IsActive,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, email, hashed_password, role, is_active, created_on, updated_on FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.IsActive,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const listApprovers = `-- name: ListApprovers :many
SELECT id, full_name FROM users
WHERE role = 'Approver' AND is_active = true
ORDER BY full_name
`

type ListApproversRow struct {
	ID       uuid.UUID
	FullName string
}

func (q *Queries) ListApprovers(ctx context.Context) ([]ListApproversRow, error) {
	rows, err := q.db.QueryContext(ctx, listApprovers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApproversRow
	for rows.Next() {
		var i ListApproversRow
		if err := rows.Scan(&i.ID, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, email, hashed_password, role, is_active, created_on, updated_on FROM users
WHERE ($3::boolean IS NULL OR is_active = $3)
ORDER BY full_name
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit    int32
	Offset   int32
	IsActive *bool
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.HashedPassword,
			&i.Role,
			&i.IsActive,
			&i.CreatedOn,
			&i.UpdatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
